import type { SuiviCategory } from "./suiviTypes";

export const suiviCategories: SuiviCategory[] = [
  {
    id: "cognitif",
    label: "Fonctionnement cognitif",
    description: "Concentration, impulsivité, démarrage, oublis.",
    status: "active",
    enabled: true,
  },
  {
    id: "emotions",
    label: "Émotions",
    description: "Humeur, stress, anxiété, irritabilité.",
    status: "active",
    enabled: true,
  },
  {
    id: "autisme",
    label: "Autisme",
    description: "Sensoriel, surcharge, masquage, communication.",
    status: "active",
    enabled: true,
  },
  {
    id: "physique",
    label: "État physique",
    description: "Énergie, fatigue, douleurs, sommeil.",
    status: "active",
    enabled: true,
  },
  {
    id: "sommeil",
    label: "Sommeil",
    description: "Coucher, réveil, réveils nocturnes.",
    status: "active",
    enabled: true,
  },
  {
    id: "journal",
    label: "Journal libre",
    description: "Texte libre pour garder le contexte.",
    status: "active",
    enabled: false,
  },
  {
    id: "evenements",
    label: "Crises et événements",
    description: "Meltdown, shutdown, anxiété, hyperfocus.",
    status: "active",
    enabled: false,
  },
  {
    id: "activite",
    label: "Activité physique",
    description: "Pas, durée, dehors, ressenti.",
    status: "inactive",
    enabled: false,
  },
  {
    id: "hygiene",
    label: "Hygiène personnelle",
    description: "Dents, douche, soins.",
    status: "inactive",
    enabled: false,
  },
  {
    id: "alimentation",
    label: "Alimentation & hydratation",
    description: "Repas, eau, déshydratation.",
    status: "inactive",
    enabled: false,
  },
  {
    id: "digestion",
    label: "Toilettes & digestion",
    description: "Transit, confort, Bristol.",
    status: "inactive",
    enabled: false,
  },
  {
    id: "travail",
    label: "Travail",
    description: "Temps travaillé, tâches, charge mentale.",
    status: "inactive",
    enabled: false,
  },
  {
    id: "therapies",
    label: "Thérapies",
    description: "Séances, objectifs, exercices.",
    status: "inactive",
    enabled: false,
  },
  {
    id: "medicaments",
    label: "Médicaments",
    description: "Prises, effets, observance.",
    status: "inactive",
    enabled: false,
  },
  {
    id: "cycle",
    label: "Cycle menstruel",
    description: "Règles, symptômes, estimations.",
    status: "inactive",
    enabled: false,
  },
];